---
title: "clustering"
author: "Amanda Freitas"
date: "2023-05-17"
output: html_document
---

```{r}
#install.packages("igraph")
#install.packages("statGraph")
#install.packages("purrr")
#install.packages("stats")
#install.packages("factoextra")
#install.packages("cluster")
```

```{r}
library(igraph)
library(statGraph)
library(purrr)
library(stats)
library(factoextra)
library(cluster)
```

# GENERATING GRAPHS

We generated 6 Erdös-Rényi graphs, with n between 50 and 70 and p between 0.15 and 0.4.

We generated 6 Watts-Strogatz graphas, with dim = 1, size between 50 and 100, nei between 3 nd 6, and p between 0.04 and 0.07.

We generated 6 Barabasi-Albert graphs, with nodes between 100 and 200, power betweet 0.3 and 0.6, and m=2.

```{r}
set.seed(19)
k <- 6

# erdos-renyi graphs
n_erdos <- sample(50:70, 6, replace = F)
p_erdos <- runif(6, 0.01, 0.4)


erdos_graphs <- map(1:k, ~erdos.renyi.game(n = n_erdos,
                                           p = p_erdos))

#watts-strogatz graphs
dim_watts <- 1
size_watts <- sample(50:100, 6, replace = F)
nei_watts <- runif(6, 3, 6)
p_watts <- runif(6, 0.04, 0.07)

watts_graphs <- map(1:k, ~sample_smallworld(dim = dim_watts,
                                            size = size_watts,
                                            nei = nei_watts,
                                            p = p_watts,
                                            loops = F))
#barabasi albert graphs
n_barabasi <- sample(100:200, replace = F)
p_barabasi <- sample(0.3:0.6, replace = F)
m_barabasi <- 2

barabasi_graphs <- map(1:k, 
                       ~barabasi.game(n = n_barabasi,
                                      power = p_barabasi,
                                      m = m_barabasi,
                                      directed = F))

#joining graphs in a single list
graphs <- c(erdos_graphs, watts_graphs, barabasi_graphs)
```


# graph_k_means

```{r}
#inputs - list of graphs, k number of clusters
k_means <- graph.kmeans(graphs, k = 3)
```

# graph.cem

```{r}
#inputs - list of graphs, random graph models, k number of clusters, maximum number of expectation-maximization steps to execute
cem <- graph.cem(graphs,
          model = "ER",
          k = 3,
          max_iter = 3)
```
# Clustering Evaluation


```{r}
silhouette_score_kmeans <- silhouette(k_means, graphs)
```


